#ifndef PKMNTEXT_H
#define PKMNTEXT_H

/* Because names and dialogue contain special characters such as (Pk) and (Mn),
 * text will be represented as an array of characters from this enum. */
typedef enum
{
 	// Used mostly as a filler to represent no character
	PKMN_CHAR_NULL,

	// Uppercase letters
	PKMN_CHAR_UPPER_A,
	PKMN_CHAR_UPPER_B,
	PKMN_CHAR_UPPER_C,
	PKMN_CHAR_UPPER_D,
	PKMN_CHAR_UPPER_E,
	PKMN_CHAR_UPPER_F,
	PKMN_CHAR_UPPER_G,
	PKMN_CHAR_UPPER_H,
	PKMN_CHAR_UPPER_I,
	PKMN_CHAR_UPPER_J,
	PKMN_CHAR_UPPER_K,
	PKMN_CHAR_UPPER_L,
	PKMN_CHAR_UPPER_M,
	PKMN_CHAR_UPPER_N,
	PKMN_CHAR_UPPER_O,
	PKMN_CHAR_UPPER_P,
	PKMN_CHAR_UPPER_Q,
	PKMN_CHAR_UPPER_R,
	PKMN_CHAR_UPPER_S,
	PKMN_CHAR_UPPER_T,
	PKMN_CHAR_UPPER_U,
	PKMN_CHAR_UPPER_V,
	PKMN_CHAR_UPPER_W,
	PKMN_CHAR_UPPER_X,
	PKMN_CHAR_UPPER_Y,
	PKMN_CHAR_UPPER_Z,

	// Lowercase letters
	PKMN_CHAR_LOWER_A,
	PKMN_CHAR_LOWER_B,
	PKMN_CHAR_LOWER_C,
	PKMN_CHAR_LOWER_D,
	PKMN_CHAR_LOWER_E,
	PKMN_CHAR_LOWER_F,
	PKMN_CHAR_LOWER_G,
	PKMN_CHAR_LOWER_H,
	PKMN_CHAR_LOWER_I,
	PKMN_CHAR_LOWER_J,
	PKMN_CHAR_LOWER_K,
	PKMN_CHAR_LOWER_L,
	PKMN_CHAR_LOWER_M,
	PKMN_CHAR_LOWER_N,
	PKMN_CHAR_LOWER_O,
	PKMN_CHAR_LOWER_P,
	PKMN_CHAR_LOWER_Q,
	PKMN_CHAR_LOWER_R,
	PKMN_CHAR_LOWER_S,
	PKMN_CHAR_LOWER_T,
	PKMN_CHAR_LOWER_U,
	PKMN_CHAR_LOWER_V,
	PKMN_CHAR_LOWER_W,
	PKMN_CHAR_LOWER_X,
	PKMN_CHAR_LOWER_Y,
	PKMN_CHAR_LOWER_Z,

	// Numbers
	PKMN_CHAR_ZERO,
	PKMN_CHAR_ONE,
	PKMN_CHAR_TWO,
	PKMN_CHAR_THREE,
	PKMN_CHAR_FOUR,
	PKMN_CHAR_FIVE,
	PKMN_CHAR_SIX,
	PKMN_CHAR_SEVEN,
	PKMN_CHAR_EIGHT,
	PKMN_CHAR_NINE,

	// Punctuation
	PKMN_CHAR_OPEN_PAREN,
	PKMN_CHAR_CLOSE_PAREN,
	PKMN_CHAR_COLON,
	PKMN_CHAR_SEMICOLON,
	PKMN_CHAR_OPEN_BRAK,
	PKMN_CHAR_CLOSE_BRAK,
	PKMN_CHAR_APOS,
	PKMN_CHAR_DASH,
	PKMN_CHAR_QUESTION,
	PKMN_CHAR_EXCLAM,
	PKMN_CHAR_DOT,
	PKMN_CHAR_SLASH,
	PKMN_CHAR_COMMA,
	PKMN_CHAR_SPACE,

	// Special characters
	PKMN_CHAR_ACCENT_E,
	PKMN_CHAR_APOS_S,
	PKMN_CHAR_PK,
	PKMN_CHAR_MN,
	PKMN_CHAR_MALE,
	PKMN_CHAR_FEMALE,
	PKMN_CHAR_POKEDOLLARS

} PkmnText;

void pkmntext_copyToStr(char* dest, PkmnText* src);
void pkmntext_copyFromStr(PkmnText* dest, char* src);

#endif
